name: Tigger Docs Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/eisen-ai/eisen-docs/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_TOKEN }} \
          --data '{"event_type": "push", "client_payload": { "repository": "Eisen-docs" }}'
